; DS2 APAS Memory Costs v1.0.3
; Restart the game after changing this file.

[APASMemoryCosts]
Enabled=1

; APAS Memory cost applied to all loaded APAS Enhancements.
; 0 = free
; 1 = one APAS Memory point per enhancement
; Valid range: 0..1000000
GlobalCost=1
