#include "windows.h"
extern "C" void* memcpy(void*d,const void*s,SIZE_T n){u8*a=(u8*)d;const u8*b=(const u8*)s;for(SIZE_T i=0;i<n;i++)a[i]=b[i];return d;}
extern "C" void* memset(void*d,int v,SIZE_T n){u8*a=(u8*)d;for(SIZE_T i=0;i<n;i++)a[i]=(u8)v;return d;}
#define TARGET_RVA 0x1E1335DULL
#define EXPECTED_TIMESTAMP 0x6A3DAE46UL
#define EXPECTED_IMAGE 0x0B292000UL
#define LOG_PATH L"C:\\Users\\Simon\\Documents\\DEATH STRANDING 2 - ON THE BEACH\\freight_likes_booster.log"
#define DR0 0x48
#define DR6 0x68
#define DR7 0x70
#define RCXOFF 0x80
#define RDXOFF 0x88
#define R8OFF 0xB8
#define RBXOFF 0x90
#define R9OFF 0xC0
#define RSPOFF 0x98
#define RIPOFF 0xF8
#define EFLAGSOFF 0x44
#define MAX_HITS 8
static HMODULE g_self,g_mod; static LPVOID g_veh; static volatile LONG g_lock,g_hit,g_active,g_seq,g_pending,g_effects; static volatile u64 g_lastRecord,g_lastPre,g_extraLikes=5000;
static u64 len(const char*s){u64 n=0;while(s&&s[n])n++;return n;} static void loadConfig(){g_extraLikes=5000;WCHAR path[520],buf[64];DWORD n=GetModuleFileNameW(g_self,path,520);if(!n||n>=520)return;DWORD slash=0;for(DWORD i=0;i<n;i++)if(path[i]=='\\'||path[i]=='/')slash=i+1;if(!slash)return;const WCHAR name[]=L"freight_likes_booster_ds2_production.ini";DWORD j=0;while(name[j]&&slash+j+1<520){path[slash+j]=name[j];j++;}if(name[j])return;path[slash+j]=0;DWORD got=GetPrivateProfileStringW(L"FreightLikesBooster",L"ExtraLikes",L"",buf,64,path);if(!got||got>=64)return;u64 v=0;for(DWORD i=0;i<got;i++){if(buf[i]<'0'||buf[i]>'9')return;v=v*10+(u64)(buf[i]-'0');if(v>1000000)return;}if(v)g_extraLikes=v;} static void ap(char*d,u32 c,const char*s){u32 n=(u32)len(d);while(s&&*s&&n+1<c)d[n++]=*s++;d[n]=0;} static void hx(char*d,u32 c,u64 v){char x[17];ap(d,c,"0x");for(int i=15;i>=0;i--){u8 q=(u8)(v&15);x[i]=(char)(q<10?'0'+q:'A'+q-10);v>>=4;}x[16]=0;ap(d,c,x);} static void dc(char*d,u32 c,u64 v){char x[24];u32 n=0;if(!v)x[n++]='0';while(v&&n<23){x[n++]=(char)('0'+v%10);v/=10;}while(n){char z[2]={x[--n],0};ap(d,c,z);}}
static bool canon(u64 p){return p>=0x10000&&p<0x800000000000ULL;} static bool rd(u64 p,void*o,u64 n){if(!canon(p)||!o||!n)return false;MEMORY_BASIC_INFORMATION m;memset(&m,0,sizeof(m));if(VirtualQuery((LPCVOID)(ULONG_PTR)p,&m,sizeof(m))!=sizeof(m)||m.State!=MEM_COMMIT||(m.Protect&PAGE_GUARD))return false;DWORD q=m.Protect&255;if(q!=2&&q!=4&&q!=8&&q!=32&&q!=64&&q!=128)return false;u64 e=(u64)(ULONG_PTR)m.BaseAddress+m.RegionSize;if(e<p||e-p<n)return false;SIZE_T got=0;return ReadProcessMemory(GetCurrentProcess(),(LPCVOID)(ULONG_PTR)p,o,(SIZE_T)n,&got)&&got==n;} static u64 q(u64 p,bool*ok){u64 v=0;*ok=rd(p,&v,8);return v;}
static u64 cg(CONTEXT*c,u32 o){u64 v=0;memcpy(&v,c->raw+o,8);return v;} static void cs(CONTEXT*c,u32 o,u64 v){memcpy(c->raw+o,&v,8);} static void writeLog(const char*s){while(InterlockedCompareExchange(&g_lock,1,0)!=0)Sleep(0);HANDLE f=CreateFileW(LOG_PATH,GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,0,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,0);if(f==INVALID_HANDLE_VALUE)f=CreateFileW(LOG_PATH,GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,0,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,0);if(f!=INVALID_HANDLE_VALUE){SetFilePointer(f,0,0,FILE_END);DWORD n=0;WriteFile(f,s,(DWORD)len(s),&n,0);FlushFileBuffers(f);CloseHandle(f);}InterlockedExchange(&g_lock,0);}
static void effectLog(u64 caller,u64 r9,u64 pre,u64 in,u64 out,bool applied){char b[900];b[0]=0;ap(b,sizeof(b),"SEQ=");dc(b,sizeof(b),(u64)InterlockedIncrement(&g_seq));ap(b,sizeof(b),"\tMARKER=WO049_EFFECT_DECISION\tCALLER_RVA=");if(caller>=(u64)(ULONG_PTR)g_mod&&caller<(u64)(ULONG_PTR)g_mod+EXPECTED_IMAGE)hx(b,sizeof(b),caller-(u64)(ULONG_PTR)g_mod);else ap(b,sizeof(b),"OUTSIDE");ap(b,sizeof(b),"\tR9=");hx(b,sizeof(b),r9);ap(b,sizeof(b),"\tPRE=");hx(b,sizeof(b),pre);ap(b,sizeof(b),"\tIN=");hx(b,sizeof(b),in);ap(b,sizeof(b),"\tOUT=");hx(b,sizeof(b),out);ap(b,sizeof(b),"\tAPPLIED=");ap(b,sizeof(b),applied?"1":"0");ap(b,sizeof(b),"\tEFFECTS=");dc(b,sizeof(b),(u64)g_effects);ap(b,sizeof(b),"\r\n");writeLog(b);}
static void gate(const char*m,u64 a,u64 b){char x[260];x[0]=0;ap(x,sizeof(x),"SEQ=");dc(x,sizeof(x),(u64)InterlockedIncrement(&g_seq));ap(x,sizeof(x),"\tMARKER=");ap(x,sizeof(x),m);ap(x,sizeof(x),"\tA=");hx(x,sizeof(x),a);ap(x,sizeof(x),"\tB=");hx(x,sizeof(x),b);ap(x,sizeof(x),"\r\n");writeLog(x);}
static bool valid(){u64 b=(u64)(ULONG_PTR)g_mod;u32 po=0,s=0,ts=0,im=0;return rd(b+0x3c,&po,4)&&po<0x1000&&rd(b+po,&s,4)&&s==0x4550&&rd(b+po+8,&ts,4)&&ts==EXPECTED_TIMESTAMP&&rd(b+po+0x50,&im,4)&&im==EXPECTED_IMAGE;}
static LONG WINAPI veh(EXCEPTION_POINTERS*e){if(!e||!e->ExceptionRecord||!e->ContextRecord||e->ExceptionRecord->ExceptionCode!=EXCEPTION_SINGLE_STEP)return EXCEPTION_CONTINUE_SEARCH;CONTEXT*c=e->ContextRecord;u64 dr6=cg(c,DR6),rip=cg(c,RIPOFF),target=(u64)(ULONG_PTR)g_mod+TARGET_RVA;DWORD tid=GetCurrentThreadId();if(!g_active)return EXCEPTION_CONTINUE_SEARCH;if(g_pending==(LONG)tid&&rip!=target){cs(c,EFLAGSOFF,cg(c,EFLAGSOFF)&~0x100ULL);cs(c,DR6,0);cs(c,DR7,cg(c,DR7)|1ULL);g_pending=0;return EXCEPTION_CONTINUE_EXECUTION;}if(!(dr6&1)||rip!=target)return EXCEPTION_CONTINUE_SEARCH;cs(c,DR6,0);cs(c,DR7,cg(c,DR7)&~1ULL);LONG n=InterlockedIncrement(&g_hit);if(n<=MAX_HITS){u64 sp=cg(c,RSPOFF),in=cg(c,RCXOFF),r8=cg(c,R8OFF),r9=cg(c,R9OFF),rbx=cg(c,RBXOFF);bool ok=0;u64 caller=q(sp,&ok),pre=0;bool preok=false;if(canon(r9))pre=q(r9,&preok);bool eligible=ok&&caller==(u64)(ULONG_PTR)g_mod+0x1E14C74ULL&&rbx==0x22&&r8==0&&preok&&pre<=0xFFFFFFFFFFFFFFDDULL&&in==pre+rbx&&in<=0x7FFFFFFFFFFFFFFFULL-g_extraLikes&&(g_lastRecord!=r9||g_lastPre!=pre);u64 out=eligible?in+g_extraLikes:in;if(eligible){cs(c,RCXOFF,out);g_lastRecord=r9;g_lastPre=pre;InterlockedIncrement(&g_effects);effectLog(caller,r9,pre,in,out,true);}if(n<MAX_HITS){g_pending=(LONG)tid;cs(c,EFLAGSOFF,cg(c,EFLAGSOFF)|0x100ULL);}else g_active=0;}return EXCEPTION_CONTINUE_EXECUTION;}
static bool bp(DWORD tid,bool en){if(tid==GetCurrentThreadId())return false;if(en && (LONG)tid==g_pending)return false;HANDLE h=OpenThread(THREAD_SUSPEND_RESUME|THREAD_GET_CONTEXT|THREAD_SET_CONTEXT|THREAD_QUERY_INFORMATION,FALSE,tid);if(!h)return false;SuspendThread(h);CONTEXT c;memset(&c,0,sizeof(c));DWORD fl=CONTEXT_CONTROL|CONTEXT_INTEGER|CONTEXT_DEBUG_REGISTERS;memcpy(c.raw+0x30,&fl,4);bool ok=GetThreadContext(h,&c);if(ok){cs(&c,DR0,en?(u64)(ULONG_PTR)g_mod+TARGET_RVA:0);cs(&c,DR6,0);u64 d=cg(&c,DR7);cs(&c,DR7,en?(d|1):(d&~1ULL));ok=SetThreadContext(h,&c);}ResumeThread(h);CloseHandle(h);return ok;}
static void scan(bool en){HANDLE s=CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD,0);if(s==INVALID_HANDLE_VALUE)return;THREADENTRY32 t;memset(&t,0,sizeof(t));t.dwSize=sizeof(t);DWORD p=GetCurrentProcessId();if(Thread32First(s,&t)){do{if(t.th32OwnerProcessID==p)bp(t.th32ThreadID,en);t.dwSize=sizeof(t);}while(Thread32Next(s,&t));}CloseHandle(s);}
static DWORD WINAPI worker(LPVOID){gate("WO049_WAITING_FOR_DS2",TARGET_RVA,EXPECTED_IMAGE);for(u32 t=0;t<120000&&!g_mod;t+=250){g_mod=GetModuleHandleW(0);if(!g_mod)Sleep(250);}if(!g_mod){gate("WO049_DS2_TIMEOUT",0,TARGET_RVA);return 0;}gate("WO049_DS2_FOUND",(u64)(ULONG_PTR)g_mod,TARGET_RVA);if(!valid()){gate("WO049_DS2_GUARD_FAIL",(u64)(ULONG_PTR)g_mod,EXPECTED_TIMESTAMP);return 0;}gate("WO049_DS2_GUARD_PASS",(u64)(ULONG_PTR)g_mod,EXPECTED_IMAGE);g_veh=AddVectoredExceptionHandler(1,veh);if(!g_veh){gate("WO049_VEH_INSTALL_FAIL",0,0);return 0;}loadConfig();g_active=1;scan(1);gate("WO049_BREAKPOINT_ACTIVE",(u64)(ULONG_PTR)g_mod+TARGET_RVA,TARGET_RVA);for(u32 t=0;t<120000&&g_active;t+=250){scan(1);Sleep(250);}g_active=0;scan(0);RemoveVectoredExceptionHandler(g_veh);g_veh=0;gate(g_hit?"WO049_HIT_COMPLETE":"WO049_NO_HIT",g_hit,TARGET_RVA);return 0;}
extern "C" __declspec(dllexport) BOOL WINAPI DllMain(HMODULE module,DWORD r,LPVOID){if(r==1){g_self=module;DisableThreadLibraryCalls(module);HANDLE t=CreateThread(0,0,worker,0,0,0);if(t)CloseHandle(t);}return TRUE;}
