[Range]
; 1 = enabled, 0 = disabled
Enabled=1

; Multiplies the vanilla BT umbilical cord cutting range.
; Vanilla internal value is 4.0.
; 1.0 = vanilla
; 2.0 = 2x vanilla
; 5.0 = 5x vanilla
; 10.0 = 10x vanilla
; Allowed range: 1.0 to 50.0
Multiplier=5.0
